import { createUseQueriesProxy } from "@trpc/react-query/shared";
import { IAgoraRTC, IAgoraRTCRemoteUser, ICameraVideoTrack, IRemoteVideoTrack } from "agora-rtc-sdk-ng";
import { useAtom } from "jotai";
import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useRef, useState } from "react";
import { useForm } from "react-hook-form";
import { any, string } from "zod";
import { userIdAtom } from "../";
import { trpc } from "../../utils/trpc";
import {Countdown} from "react-daisyui";
//import AgoraRTC from "agora-rtc-sdk-ng";
//import createClient from "agora-rtc-sdk-ng";

const APP_ID = process.env.NEXT_PUBLIC_AGORA_APP_ID!;
type Props = {
  videoTrack: ICameraVideoTrack | IRemoteVideoTrack;
};

export const VideoPlayer = ({videoTrack}: Props) => {


  const ref = useRef(null);

  useEffect(()=> {

    const playerRef = ref.current;
    if (!videoTrack) return;
    if (!playerRef) return;

    videoTrack.play(playerRef);

    return () => {
      videoTrack.stop();
    }
  }, [])

  return (
    <div className="flex items-center justify-center">
      <div ref={ref} className='w-[250px] h-[250px]'></div>
    </div>
  )
}

const ChattingPage: NextPage = () => {
  const [timeLeft, setTimeLeft] = useState<number>(25);

  useEffect(() => {
    const timer = setTimeout(() => {
      setTimeLeft((v) => (v <= 0 ? 25 : v - 1))
    }, 1000)

    return () => {
      clearTimeout(timer)
    }
  }, [timeLeft])

  const promiseRef = useRef<any>(Promise.resolve());
  const router = useRouter()
  const matchId = router.query.matchId as string;
  const [userId] = useAtom(userIdAtom)
  const [otherUser, setOtherUser] = useState<IAgoraRTCRemoteUser>();
  const [videoTrack, setVideoTrack] = useState<ICameraVideoTrack>()

  const matchQuery = trpc.matches.getMatch.useQuery({matchId});
  const tokenQuery = trpc.matches.getToken.useQuery({userId, matchId}, {
    refetchOnWindowFocus: false
  });

  const isEndUser = matchQuery.data?.endUserId === userId;
  let otherUserName = '';


  
  if (matchQuery.data) {
    otherUserName = isEndUser ? matchQuery.data.endUser.name : matchQuery.data.sourceUser.name
  }
  
  useEffect(() => {

    if(!userId) {
      router.push('/')
      return;
    }

    
    if(!tokenQuery.data) return;
    if(!matchId) return;
    


    // connect to agora video room
    const connect = async() => {
      const { default: AgoraRTC } = await import("agora-rtc-sdk-ng");

      
      const token = tokenQuery.data;

      const client = AgoraRTC.createClient({
        mode:"rtc",
        codec: "vp8",
      })

     await client.join(
        APP_ID,
        matchId,
        token,
        userId,
      );
  

    client.on("user-published", (user: any, mediaType: any) => {
      client.subscribe(user, mediaType).then(() => {
        if (mediaType === "video") {
          
          setOtherUser(user)
        }
    }
      )
    })

    
    const tracks = await AgoraRTC.createMicrophoneAndCameraTracks();
    setVideoTrack(tracks[1]);
    await client.publish(tracks[1]);
    
    return {tracks, client}
  }

    promiseRef.current = promiseRef.current.then(connect);

    return () => {
      const disconnect = async () => {

        const {client, tracks} = await promiseRef.current;
        client.removeAllListeners();
        videoTrack?.stop();
        videoTrack?.close();

        await client.unpublish(tracks[1]);
        await client.leave();
      }
    promiseRef.current = promiseRef.current.then(disconnect)
    disconnect();

    }
  }, [tokenQuery.data, matchId, userId])
  

  return (
    <div>
      <Head>
        <title>Chatting with User</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main data-theme="night" className="flex flex-col items-center justify-center min-h-screen">
        
          <div className="space-y-2 md:space-y-4 p-2 flex flex-col items-center mb-10">
            <h1 className="text-2xl md:text-5xl">Chatting with {`${otherUserName}`}</h1>
            <Countdown className="text-2xl md:text-5xl text-secondary" value={timeLeft} />
          </div>

          <div className="flex flex-row items-center justify-center md:space-x-10">
              <div className="hidden md:inline p-1 bg-gradient-to-r from-sky-400 to-cyan-300">
                {videoTrack && <VideoPlayer videoTrack={videoTrack} />}
              </div>
              <div className="p-1 align-center bg-gradient-to-r from-sky-400 to-cyan-300">
                {otherUser?.videoTrack && <VideoPlayer videoTrack={otherUser.videoTrack} />}
              </div>
          </div>
      </main>
    </div>
  );
};

export default ChattingPage;

