import { createUseQueriesProxy } from "@trpc/react-query/shared";
import { type NextPage } from "next";
import Head from "next/head";
import { useForm } from "react-hook-form";
import { trpc } from "../utils/trpc";
import { useRouter } from "next/router";
import {atom, useAtom} from "jotai";



const Done: NextPage = () => {
  const router = useRouter();
  

  return (
    <div>
      <Head>
        <title>Video Chat Done</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main data-theme="night" className="flex flex-col items-center justify-center min-h-screen">
      
      <h1 className="text-5xl font-semibold bg-gradient-to-r from-sky-400 to-cyan-300 text-transparent bg-clip-text p-4 mb-10">Video Chat Done</h1>
        <button onClick={() => router.push("/waiting")} className="btn bg-gradient-to-r from-sky-400 to-cyan-300 mt-10 text-black max-w-2xl">Go to Waiting Room</button>
        
      </main>
    </div>
  );
};

export default Done;

